services:
  opensearch-node:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_JAVA_OTPS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  backend:
    build:
      context: ./Test-Technique-backend
    depends_on:
      - opensearch-node
    environment:
      - OPENSEARCH_HOST=opensearch-node
      - OPENSEARCH_USER=admin
      - OPENSEARCH_PASS=admin
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./Test-Technique-Frontend
    depends_on:
      - backend
    ports:
      - "4173:4173"

volumes:
  opensearch-data: